CREATE TABLE events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    NOSAUKUMS VARCHAR(255) NOT NULL,
    APRAKSTS TEXT NOT NULL,
    CENA DECIMAL(10, 2) NOT NULL,
    BILDE VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VECUMS INT(2) NOT NULL,
    VECUMS2 INT(2) NOT NULL,
    DZIMUMS VARCHAR(25) NOT NULL,
    KATEGORIJA VARCHAR(100) NOT NULL
);

CREATE TABLE forum_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE forum_replies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    post_id INT NOT NULL,
    username VARCHAR(100) NOT NULL,
    reply TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES forum_posts(id) ON DELETE CASCADE
);

CREATE TABLE atsauksmes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pasakuma_id INT NOT NULL,
    lietotajvards VARCHAR(255) NOT NULL,
    atsauksme TEXT,
    reitings INT CHECK (reitings BETWEEN 1 AND 5),
    datums DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,          -- which user "owns" the notification
  message TEXT,         -- notification text
  status VARCHAR(20),   -- e.g. 'pending', 'accepted', 'rejected'
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
